version: 0.2

phases:
  build:
    commands:
      - echo Entered the build phase...
      - echo Build started on `date`
      - echo Writing image definitions file...
      - printf '[{"name":"%s","imageUri":"%s"}]' "bbb" "667736119737.dkr.ecr.us-east-1.amazonaws.com/nginx:latest" | tee imagedefinitions.json

artifacts:
  files: 
    - '**/*'